name: build-and-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd app
        npm install
        npm audit
        npm audit fix --force || true

    - name: Run TruffleHog (Secrets scan)
      uses: trufflesecurity/trufflehog@main
      with:
        scanArguments: --path=.

    - name: Run Semgrep (SAST)
      uses: returntocorp/semgrep-action@v1
      with:
        config: "auto"

    - name: Build Docker image
      run: docker build -t juice-shop-devsecops:latest .

    - name: Run Trivy (Docker image scan)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'juice-shop-devsecops:latest'
        format: 'table'
        severity: 'HIGH,CRITICAL'

    - name: Run ZAP Baseline Scan (DAST)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://juice-shop.herokuapp.com'
