# .github/workflows/devsecops.yml
name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: CI and Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd app
          npm install --no-audit --no-fund --legacy-peer-deps || true

      - name: Lint with ESLint
        run: |
          cd app
          npx eslint . || true

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "juice-shop"
          path: "./app"
          format: "SARIF"
          out: "reports"

      - name: Upload dependency-check SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/dependency-check-report.sarif

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/yaroslavstarzhynsky/juice-shop:local-scan ./app

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Final Image
        run: |
          docker tag ghcr.io/yaroslavstarzhynsky/juice-shop:local-scan ghcr.io/yaroslavstarzhynsky/juice-shop:latest
          docker tag ghcr.io/yaroslavstarzhynsky/juice-shop:local-scan ghcr.io/yaroslavstarzhynsky/juice-shop:${{ github.sha }}
          docker push ghcr.io/yaroslavstarzhynsky/juice-shop:latest
          docker push ghcr.io/yaroslavstarzhynsky/juice-shop:${{ github.sha }}

