name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  sast:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"

  secrets:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install --no-audit --no-fund --legacy-peer-deps --package-lock
          else
            echo "No package.json found, skipping install."
          fi
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "juice-shop"
          format: "SARIF"
          out: "reports"
      - name: Ensure SARIF exists
        run: |
          if [ ! -f reports/dependency-check-report.sarif ]; then
            echo "Missing SARIF report!" && exit 1
          fi
      - name: Upload Dependency-Check results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
